### ISSUE TITLE
I got these error.

### ISSUE THREAD

**Issue by quintendewilde** [cheesymoo/simple-neuron-max-msp#1]
2015-02-28 18:56:45.797 Max[1204:120465] Error loading simple-neuron-max-msp-master 2/simpleNeuron.mxo/Contents/MacOS/simpleNeuron:  dlopen(simple-neuron-max-msp-master 2/simpleNeuron.mxo/Con
 tents/MacOS/simpleNeuron, 262): no suitable image found.  Did find:
    /Users/quintendewilde/Downloads/simple-neuron-max-msp-master 2/simpleNeuron.mxo/Contents/MacOS/simpleNeuron: mach-o, but wrong architecture

Additionally i received this error: ezdac~ doesn't understand "float"
and this one to : simpleNeuron: unable to load object bundle executable

**Comment by cheesymoo** [comment]
As far as the first error:
What operating system/version are you running?
Did you build the .mxo yourself?

As far as the ezdac~ error, I would have to look at your patch. My guess is that you are outputting the simple-neuron object directly to the ezdac~ which would not work. The simple-neuron object outputs a bang, so you could use it to trigger a different sound source, not send it to the dac directly.

**Comment by quintendewilde** [comment]
I have the patch for jou.

{
    "boxes" : [         {
            "box" :             {
                "maxclass" : "newobj",
                "text" : "click~",
                "outlettype" : [ "signal" ],
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-21",
                "numoutlets" : 1,
                "patching_rect" : [ 223.0, 272.0, 41.0, 22.0 ]
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "ezdac~",
                "prototypename" : "helpfile",
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-33",
                "numoutlets" : 0,
                "local" : 1,
                "patching_rect" : [ 211.0, 382.0, 44.0, 44.0 ]
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "live.gain~",
                "varname" : "level",
                "parameter_enable" : 1,
                "outlettype" : [ "signal", "", "float", "list" ],
                "channels" : 1,
                "presentation_rect" : [ 15.0, 15.0, 50.0, 41.0 ],
                "numinlets" : 1,
                "orientation" : 1,
                "id" : "obj-3",
                "numoutlets" : 4,
                "patching_rect" : [ 223.0, 315.0, 136.0, 41.0 ],
                "saved_attribute_attributes" :              {
                    "valueof" :                     {
                        "parameter_longname" : "level",
                        "parameter_shortname" : "level",
                        "parameter_type" : 0,
                        "parameter_mmin" : -70.0,
                        "parameter_mmax" : 6.0,
                        "parameter_initial" : [ 0.0 ],
                        "parameter_unitstyle" : 4
                    }

```
            }

        }

    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Metro acts as constant input source",
                "linecount" : 2,
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-20",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 88.0, 64.0, 150.0, 33.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Banging input displays\ncurrent values and mode",
                "linecount" : 2,
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-19",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 85.0, 202.0, 150.0, 33.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Bangs when neuron fires",
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-18",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 251.0, 236.0, 150.0, 20.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Voltage Threshold",
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-17",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 359.0, 153.0, 150.0, 20.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Capacitance",
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-16",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 357.0, 119.0, 150.0, 20.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Resistance",
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-15",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 356.0, 86.0, 150.0, 20.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "comment",
                "text" : "Mode 0: IF Oscillator\nMode 1: LIF Oscillator\nMode 2: FitzHugh-Nagumo",
                "linecount" : 3,
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-14",
                "fontsize" : 12.0,
                "numoutlets" : 0,
                "patching_rect" : [ 221.0, 34.0, 164.0, 47.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "toggle",
                "parameter_enable" : 0,
                "outlettype" : [ "int" ],
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-13",
                "numoutlets" : 1,
                "patching_rect" : [ 162.0, 85.0, 20.0, 20.0 ]
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "newobj",
                "text" : "metro 100",
                "outlettype" : [ "bang" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-11",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 162.0, 122.0, 65.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "Vth 5",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-9",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 315.0, 155.0, 39.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "mode 2",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-12",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 251.0, 155.0, 51.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "C 1",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-10",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 314.0, 122.0, 32.5, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "R 20.",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-8",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 313.0, 85.0, 39.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "mode 1",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-7",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 239.0, 122.0, 51.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "mode 0",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-6",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 225.0, 85.0, 51.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "button",
                "outlettype" : [ "bang" ],
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-5",
                "numoutlets" : 1,
                "patching_rect" : [ 223.0, 236.0, 20.0, 20.0 ]
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "button",
                "outlettype" : [ "bang" ],
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-4",
                "numoutlets" : 1,
                "patching_rect" : [ 163.0, 179.0, 20.0, 20.0 ]
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "message",
                "text" : "1.",
                "outlettype" : [ "" ],
                "numinlets" : 2,
                "style" : "",
                "id" : "obj-2",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 162.0, 155.0, 50.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

,       {
            "box" :             {
                "maxclass" : "newobj",
                "text" : "simpleNeuron",
                "outlettype" : [ "" ],
                "numinlets" : 1,
                "style" : "",
                "id" : "obj-1",
                "fontsize" : 12.0,
                "numoutlets" : 1,
                "patching_rect" : [ 223.0, 198.0, 85.0, 22.0 ],
                "fontname" : "Arial"
            }

```
    }
```

 ],
    "lines" : [         {
            "patchline" :           {
                "source" : [ "obj-9", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 324.5, 183.0, 232.5, 183.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-8", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 322.5, 105.0, 300.0, 105.0, 300.0, 150.0, 303.0, 150.0, 303.0, 183.0, 232.5, 183.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-7", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 248.5, 141.0, 237.0, 141.0, 237.0, 183.0, 232.5, 183.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-6", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 234.5, 195.0, 232.5, 195.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-5", 0 ],
                "destination" : [ "obj-21", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-4", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-3", 0 ],
                "destination" : [ "obj-33", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-21", 0 ],
                "destination" : [ "obj-3", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-2", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 171.5, 174.0, 195.0, 174.0, 195.0, 183.0, 232.5, 183.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-13", 0 ],
                "destination" : [ "obj-11", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-12", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 260.5, 183.0, 232.5, 183.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-11", 0 ],
                "destination" : [ "obj-2", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-10", 0 ],
                "destination" : [ "obj-1", 0 ],
                "hidden" : 0,
                "midpoints" : [ 323.5, 141.0, 312.0, 141.0, 312.0, 183.0, 232.5, 183.0 ],
                "disabled" : 0
            }

```
    }
```

,       {
            "patchline" :           {
                "source" : [ "obj-1", 0 ],
                "destination" : [ "obj-5", 0 ],
                "hidden" : 0,
                "disabled" : 0
            }

```
    }
```

 ],
    "appversion" :  {
        "major" : 7,
        "minor" : 0,
        "revision" : 0,
        "architecture" : "x64",
        "modernui" : 1
    }

}

**Comment by quintendewilde** [comment]
The SimpleNeuron is in yellow and not in gray like the rest.

Max7 on Yosemite

**Comment by quintendewilde** [comment]
there's also no helpfile found!?

**Comment by cheesymoo** [comment]
Indeed there is no helpfile.
I have never tested on Max7 or Yosemite.

I'm going to build on Mavericks for Max7 and see what we get.

**Comment by Lazyfattree** [comment]
Superb Thanks!



De Wilde Quinten
Azaleastraat 34
9040 St. Amandsberg


K.A.S.K. - Mediakunst

**Comment by cheesymoo** [comment]
Okay, I have it running using Mavericks and Max 7. Download the new .mxo file and .maxhelp file and give it a go!

**Comment by quintendewilde** [comment]
It works!! perfect!
Thanks a lot!

**Comment by cheesymoo** [comment]
Great! I'd enjoy to see your project once you're done. :-)

**Comment by quintendewilde** [comment]
Hi,

I’m wondering how the neuron is created?

Or better how the 3 oscillators are used for the creation of the neuron “bangs”?

Do you have a file with more in-depth explanation?

My projects is working on the multiple neural ‘bangs’ to trigger stuff on an Arduino. 

Kindest Regards,

Q.!

**Comment by cheesymoo** [comment]
Here is a paper I wrote that gives the most info: https://phermans.files.wordpress.com/2013/10/hermans-m102-final.pdf

I am also updating the object to simpleNeuron~ to work as an MSP object (and have audio in/out) ... I will make more examples when that is ready

**Comment by cheesymoo** [comment]
I just uploaded 3 example patches: brainTest1, 2 and 3. Hopefully they will help

**Comment by quintendewilde** [comment]
Hey Phillip,

Could I contact you personally?

Greets,

Quinten

2015-03-03 10:17 GMT+01:00 Phillip Hermans notifications@github.com:

**Comment by cheesymoo** [comment]
You can always email :-)

**Comment by cheesymoo** [comment]
I contacted you via SoundCloud
